import { MaintenanceTicket, Technician, Appointment, NotificationItem } from './types';

export const INITIAL_TECHNICIANS: Technician[] = [
  {
    id: 'tech-carlos',
    name: 'Carlos Santos',
    team: 'Equipe Hidráulica',
    specialties: ['Hidráulica', 'Vazamentos', 'Instalações hidráulicas', 'Tubulações'],
    phone: '(11) 98765-4321',
    email: 'carlos.santos@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&q=80&w=200',
    status: 'em_atendimento',
    rating: 4.9,
    activeCount: 3,
  },
  {
    id: 'tech-joao',
    name: 'João Silva',
    team: 'Equipe Pintura',
    specialties: ['Pintura', 'Massa corrida', 'Textura', 'Restauração de fachadas'],
    phone: '(11) 97654-3210',
    email: 'joao.silva@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    status: 'disponivel',
    rating: 4.8,
    activeCount: 1,
  },
  {
    id: 'tech-jose',
    name: 'José Lima',
    team: 'Equipe Elétrica',
    specialties: ['Elétrica', 'Quadros de disjuntores', 'Tomadas e interruptores', 'Chuveiros'],
    phone: '(11) 99123-4567',
    email: 'jose.lima@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    status: 'em_atendimento',
    rating: 5.0,
    activeCount: 2,
  },
  {
    id: 'tech-pedro',
    name: 'Pedro Henrique',
    team: 'Equipe Pintura',
    specialties: ['Pintura interna', 'Verniz em madeira', 'Gesso e drywall'],
    phone: '(11) 98877-6655',
    email: 'pedro.henrique@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    status: 'disponivel',
    rating: 4.7,
    activeCount: 0,
  },
  {
    id: 'tech-marcelo',
    name: 'Marcelo Ramos',
    team: 'Equipe Hidráulica',
    specialties: ['Desentupimento', 'Válvula hydra', 'Caixas d’água', 'Estanqueidade'],
    phone: '(11) 98234-5678',
    email: 'marcelo.ramos@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
    status: 'disponivel',
    rating: 4.9,
    activeCount: 1,
  },
  {
    id: 'tech-rafael',
    name: 'Rafael Mendes',
    team: 'Equipe Revestimentos',
    specialties: ['Azulejos', 'Porcelanato', 'Pastilhas', 'Contrapiso e rejunte'],
    phone: '(11) 97345-6789',
    email: 'rafael.mendes@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
    status: 'disponivel',
    rating: 4.8,
    activeCount: 0,
  },
  {
    id: 'tech-lucas',
    name: 'Lucas Almeida',
    team: 'Equipe Esquadrias & Fechaduras',
    specialties: ['Fechaduras eletrônicas', 'Portas de madeira', 'Janelas de alumínio', 'Molas'],
    phone: '(11) 99456-7890',
    email: 'lucas.almeida@casapronta.com.br',
    avatar:
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=200',
    status: 'disponivel',
    rating: 4.9,
    activeCount: 1,
  },
];

export const INITIAL_TICKETS: MaintenanceTicket[] = [
  {
    id: 't-1024',
    protocol: '#1024',
    createdAt: '2026-09-12 10:15',
    updatedAt: '2026-09-13 11:30',
    tenantName: 'Mariana Costa',
    tenantPhone: '(11) 98123-4567',
    tenantEmail: 'mariana.costa@email.com',
    address: 'Rua das Acácias, 450 - Apto 402',
    neighborhood: 'Pinheiros, São Paulo - SP',
    propertyType: 'apartamento',
    environment: 'Cozinha',
    category: 'hidraulica',
    description:
      'Vazamento contínuo sob a pia da cozinha, molhando o armário embutido. A torneira também está com gotejamento constante mesmo fechada com força.',
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=600',
    ],
    urgency: 'alta',
    preferredPeriod: 'manha',
    status: 'orcamento_enviado',
    assignedAgencyId: 'imob-alianca',
    assignedAgencyName: 'Aliança Gestão Imobiliária',
    assignedCompanyId: 'emp-casapronta',
    assignedCompanyName: 'Casa Pronta Manutenções',
    assignedTechnicianId: 'tech-carlos',
    assignedTechnicianName: 'Carlos Santos',
    lastActionAt: '2026-09-13 11:30',
    timeline: [
      {
        id: 'tl-1',
        status: 'chamado_aberto',
        title: 'Chamado Aberto pelo Inquilino',
        description: 'Solicitação registrada no sistema com fotos e descrição do problema.',
        timestamp: '12/09/2026 às 10:15',
        authorName: 'Mariana Costa',
        authorRole: 'inquilino',
      },
      {
        id: 'tl-2',
        status: 'em_analise',
        title: 'Em Análise pela Imobiliária',
        description: 'Imobiliária verificou o contrato e autorizou vistoria técnica presencial.',
        timestamp: '12/09/2026 às 11:40',
        authorName: 'Aliança Imobiliária',
        authorRole: 'imobiliaria',
      },
      {
        id: 'tl-3',
        status: 'aguardando_vistoria',
        title: 'Vistoria Realizada pelo Prestador',
        description: 'Técnico Carlos Santos compareceu ao imóvel e emitiu o Parecer Técnico.',
        timestamp: '13/09/2026 às 09:20',
        authorName: 'Carlos Santos',
        authorRole: 'prestador',
      },
      {
        id: 'tl-4',
        status: 'orcamento_enviado',
        title: 'Orçamento Enviado para Aprovação',
        description: 'Empresa Casa Pronta enviou o orçamento detalhado no valor de R$ 380,00.',
        timestamp: '13/09/2026 às 11:30',
        authorName: 'Casa Pronta Manutenções',
        authorRole: 'empresa',
      },
    ],
    technicalReport: {
      id: 'rep-1024',
      ticketId: 't-1024',
      technicianId: 'tech-carlos',
      technicianName: 'Carlos Santos',
      createdAt: '13/09/2026 às 09:20',
      tenantProblem: 'Vazamento na parede e pia da cozinha.',
      situationFound:
        'Foi constatado vazamento na rosca do sifão e desgaste na vedação do reparo da torneira de bancada, além de leve infiltração na junção do flexível.',
      possibleCause: 'Ressecamento dos anéis de borracha e tempo útil do sifão expirado.',
      recommendedSolution:
        'Substituição completa do sifão copo por modelo metálico reforçado, troca do kit de reparo cerâmico da torneira e troca da mangueira flexível inox de 40cm.',
      requiredMaterials:
        '1 Sifão metálico copo 1.1/2", 1 Flexível inox 40cm, 1 Cartucho cerâmico M22, veda-rosca teflon.',
      needsQuote: true,
      needsReturn: false,
      recommendedPriority: 'alta',
      photos: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
      ],
    },
    quote: {
      id: 'qt-1024',
      ticketId: 't-1024',
      createdAt: '13/09/2026 às 11:30',
      serviceDescription:
        'Substituição de sifão, troca de engate flexível trançado e reparo interno da torneira com teste de pressão e estanqueidade.',
      materialsSummary:
        'Sifão copo cromado Deca, flexível malha inox, kit vedação cerâmica e fita veda-rosca.',
      laborSummary: 'Mão de obra especializada hidráulica com garantia de 90 dias.',
      materialsCost: 160.0,
      laborCost: 220.0,
      totalCost: 380.0,
      executionDeadlineDays: 1,
      notes: 'Execução estimada em 1h30 logo após a aprovação da imobiliária.',
      status: 'enviado',
    },
    chatMessages: [
      {
        id: 'msg-1',
        ticketId: 't-1024',
        senderRole: 'inquilino',
        senderName: 'Mariana Costa',
        message: 'Bom dia! O vazamento piorou um pouco durante a noite, coloquei um balde embaixo.',
        timestamp: '12/09/2026 10:20',
      },
      {
        id: 'msg-2',
        ticketId: 't-1024',
        senderRole: 'imobiliaria',
        senderName: 'Aliança Gestão',
        message:
          'Olá Mariana, já direcionamos para nossa parceira Casa Pronta. O técnico irá vistoriar.',
        timestamp: '12/09/2026 11:45',
      },
      {
        id: 'msg-3',
        ticketId: 't-1024',
        senderRole: 'empresa',
        senderName: 'Casa Pronta Manutenções',
        message:
          'Vistoria concluída com o técnico Carlos. Acabamos de disponibilizar o orçamento aqui no sistema para aprovação da imobiliária!',
        timestamp: '13/09/2026 11:32',
      },
    ],
  },
  {
    id: 't-1025',
    protocol: '#1025',
    createdAt: '2026-09-11 14:00',
    updatedAt: '2026-09-13 08:30',
    tenantName: 'Roberto Nunes',
    tenantPhone: '(11) 97234-8899',
    tenantEmail: 'roberto.nunes@email.com',
    address: 'Av. Paulista, 1200 - Apto 84',
    neighborhood: 'Bela Vista, São Paulo - SP',
    propertyType: 'apartamento',
    environment: 'Banheiro Social',
    category: 'hidraulica',
    description:
      'Infiltração no teto do banheiro com gotejamento após uso do chuveiro do apartamento superior.',
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    ],
    urgency: 'alta',
    preferredPeriod: 'tarde',
    status: 'servico_agendado',
    assignedAgencyId: 'imob-alianca',
    assignedAgencyName: 'Aliança Gestão Imobiliária',
    assignedCompanyId: 'emp-casapronta',
    assignedCompanyName: 'Casa Pronta Manutenções',
    assignedTechnicianId: 'tech-carlos',
    assignedTechnicianName: 'Carlos Santos',
    lastActionAt: '2026-09-13 08:30',
    timeline: [
      {
        id: 'tl-25-1',
        status: 'chamado_aberto',
        title: 'Chamado Aberto',
        description: 'Relatada infiltração no teto do banheiro.',
        timestamp: '11/09/2026 às 14:00',
        authorName: 'Roberto Nunes',
        authorRole: 'inquilino',
      },
      {
        id: 'tl-25-2',
        status: 'orcamento_aprovado',
        title: 'Orçamento Aprovado',
        description: 'Orçamento no valor de R$ 520,00 aprovado pela imobiliária.',
        timestamp: '12/09/2026 às 16:30',
        authorName: 'Aliança Imobiliária',
        authorRole: 'imobiliaria',
      },
      {
        id: 'tl-25-3',
        status: 'servico_agendado',
        title: 'Atendimento Agendado para Hoje',
        description: 'Serviço marcado para 13/09/2026 às 14:00 com Carlos Santos.',
        timestamp: '13/09/2026 às 08:30',
        authorName: 'Casa Pronta',
        authorRole: 'empresa',
      },
    ],
    appointment: {
      id: 'apt-1025',
      ticketId: 't-1025',
      protocol: '#1025',
      clientName: 'Roberto Nunes',
      clientPhone: '(11) 97234-8899',
      address: 'Av. Paulista, 1200 - Apto 84',
      neighborhood: 'Bela Vista, São Paulo - SP',
      agencyName: 'Aliança Gestão Imobiliária',
      serviceType: 'Reparo hidráulico e teste de estanqueidade',
      description: 'Verificação da tubulação do ralo e substituição de conexão flexível superior.',
      technicianId: 'tech-carlos',
      technicianName: 'Carlos Santos',
      teamName: 'Equipe Hidráulica',
      date: '2026-09-13',
      startTime: '14:00',
      endTime: '16:00',
      priority: 'alta',
      status: 'confirmado',
      notes: 'Interfone tocar direto no 84. Portaria já notificada.',
      tenantConfirmed: true,
    },
    quote: {
      id: 'qt-1025',
      ticketId: 't-1025',
      createdAt: '12/09/2026 às 15:00',
      serviceDescription:
        'Abertura de forro, substituição de ramal de esgoto danificado e teste com corante.',
      materialsSummary: 'Tubos PVC 50mm esgoto, cola tigre, luva de correr e vedações.',
      laborSummary: 'Técnico hidráulico predial certificado.',
      materialsCost: 190.0,
      laborCost: 330.0,
      totalCost: 520.0,
      executionDeadlineDays: 1,
      status: 'aprovado',
      approvedAt: '12/09/2026 16:30',
    },
    chatMessages: [
      {
        id: 'msg-25-1',
        ticketId: 't-1025',
        senderRole: 'empresa',
        senderName: 'Casa Pronta Manutenções',
        message:
          'Prezado Roberto, confirmamos o agendamento para hoje às 14:00 com o técnico Carlos Santos.',
        timestamp: '13/09/2026 08:35',
      },
      {
        id: 'msg-25-2',
        ticketId: 't-1025',
        senderRole: 'inquilino',
        senderName: 'Roberto Nunes',
        message: 'Perfeito! Já avisei a portaria do prédio e estarei no apartamento aguardando.',
        timestamp: '13/09/2026 08:50',
      },
    ],
  },
  {
    id: 't-1026',
    protocol: '#1026',
    createdAt: '2026-09-13 08:10',
    updatedAt: '2026-09-13 10:00',
    tenantName: 'Camila Toledo',
    tenantPhone: '(11) 98999-1122',
    tenantEmail: 'camila.toledo@email.com',
    address: 'Rua Oscar Freire, 89 - Casa 3',
    neighborhood: 'Cerqueira César, São Paulo - SP',
    propertyType: 'casa',
    environment: 'Quadro Geral e Suíte',
    category: 'eletrica',
    description:
      'Cheiro forte de plástico queimado no quadro de disjuntores e chuveiro desligou repentinamente. Luzes piscando na casa inteira.',
    photos: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=600',
    ],
    urgency: 'emergencial',
    preferredPeriod: 'integral',
    status: 'em_execucao',
    assignedAgencyId: 'imob-alianca',
    assignedAgencyName: 'Aliança Gestão Imobiliária',
    assignedCompanyId: 'emp-casapronta',
    assignedCompanyName: 'Casa Pronta Manutenções',
    assignedTechnicianId: 'tech-jose',
    assignedTechnicianName: 'José Lima',
    lastActionAt: '2026-09-13 10:00',
    timeline: [
      {
        id: 'tl-26-1',
        status: 'chamado_aberto',
        title: 'Chamado Emergencial Registrado',
        description: 'Prioridade máxima devido a risco de curto-circuito.',
        timestamp: '13/09/2026 às 08:10',
        authorName: 'Camila Toledo',
        authorRole: 'inquilino',
      },
      {
        id: 'tl-26-2',
        status: 'em_execucao',
        title: 'Serviço Iniciado pelo Eletricista',
        description: 'Técnico José Lima no local inspecionando o barramento e cabeamento.',
        timestamp: '13/09/2026 às 10:00',
        authorName: 'José Lima',
        authorRole: 'prestador',
      },
    ],
    appointment: {
      id: 'apt-1026',
      ticketId: 't-1026',
      protocol: '#1026',
      clientName: 'Camila Toledo',
      clientPhone: '(11) 98999-1122',
      address: 'Rua Oscar Freire, 89 - Casa 3',
      neighborhood: 'Cerqueira César, São Paulo - SP',
      agencyName: 'Aliança Gestão Imobiliária',
      serviceType: 'Emergência Elétrica - Quadro Geral',
      description: 'Substituição de disjuntor bipolar 40A e reaperto de barramento trifásico.',
      technicianId: 'tech-jose',
      technicianName: 'José Lima',
      teamName: 'Equipe Elétrica',
      date: '2026-09-13',
      startTime: '09:30',
      endTime: '12:00',
      priority: 'emergencial',
      status: 'em_atendimento',
      notes: 'Entrada pelo portão lateral. Chave geral desligada preventivamente.',
      tenantConfirmed: true,
    },
    chatMessages: [
      {
        id: 'msg-26-1',
        ticketId: 't-1026',
        senderRole: 'empresa',
        senderName: 'Casa Pronta Manutenções',
        message:
          'Chamado emergencial acionado imediatamente. Técnico José Lima chegou ao local às 09:45.',
        timestamp: '13/09/2026 09:48',
      },
    ],
  },
  {
    id: 't-1027',
    protocol: '#1027',
    createdAt: '2026-09-13 11:00',
    updatedAt: '2026-09-13 11:15',
    tenantName: 'Felipe Guimarães',
    tenantPhone: '(11) 97766-5544',
    tenantEmail: 'felipe.g@email.com',
    address: 'Alameda Santos, 320 - Apto 1102',
    neighborhood: 'Jardins, São Paulo - SP',
    propertyType: 'apartamento',
    environment: 'Varanda Gourmet',
    category: 'pintura',
    description:
      'Pintura da parede da varanda começou a estufar e descascar após a última tempestade com vento. Requer raspagem e repintura.',
    photos: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=600',
    ],
    urgency: 'normal',
    preferredPeriod: 'manha',
    status: 'em_analise',
    assignedAgencyId: 'imob-alianca',
    assignedAgencyName: 'Aliança Gestão Imobiliária',
    lastActionAt: '2026-09-13 11:15',
    timeline: [
      {
        id: 'tl-27-1',
        status: 'chamado_aberto',
        title: 'Chamado Aberto pelo Inquilino',
        description: 'Solicitação aguardando encaminhamento para a prestadora.',
        timestamp: '13/09/2026 às 11:00',
        authorName: 'Felipe Guimarães',
        authorRole: 'inquilino',
      },
      {
        id: 'tl-27-2',
        status: 'em_analise',
        title: 'Em Análise pela Imobiliária',
        description: 'Gestor da Imobiliária checando histórico de pintura de entrega das chaves.',
        timestamp: '13/09/2026 às 11:15',
        authorName: 'Aliança Imobiliária',
        authorRole: 'imobiliaria',
      },
    ],
    chatMessages: [
      {
        id: 'msg-27-1',
        ticketId: 't-1027',
        senderRole: 'inquilino',
        senderName: 'Felipe Guimarães',
        message: 'Gostaria de saber se podem agendar a visita para este sábado pela manhã.',
        timestamp: '13/09/2026 11:05',
      },
    ],
  },
  {
    id: 't-1028',
    protocol: '#1028',
    createdAt: '2026-09-08 09:00',
    updatedAt: '2026-09-10 17:30',
    tenantName: 'André Siqueira',
    tenantPhone: '(11) 96543-2198',
    tenantEmail: 'andre.siqueira@email.com',
    address: 'Rua das Acácias, 450 - Apto 201',
    neighborhood: 'Pinheiros, São Paulo - SP',
    propertyType: 'apartamento',
    environment: 'Entrada Principal',
    category: 'porta_fechadura',
    description:
      'Fechadura digital biométrica travando o trinco e não trancando pelo lado de fora.',
    photos: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=600',
    ],
    urgency: 'alta',
    preferredPeriod: 'tarde',
    status: 'concluido',
    assignedAgencyId: 'imob-alianca',
    assignedAgencyName: 'Aliança Gestão Imobiliária',
    assignedCompanyId: 'emp-casapronta',
    assignedCompanyName: 'Casa Pronta Manutenções',
    assignedTechnicianId: 'tech-lucas',
    assignedTechnicianName: 'Lucas Almeida',
    lastActionAt: '2026-09-10 17:30',
    timeline: [
      {
        id: 'tl-28-1',
        status: 'chamado_aberto',
        title: 'Chamado Aberto',
        description: 'Fechadura digital com defeito.',
        timestamp: '08/09/2026 às 09:00',
        authorName: 'André Siqueira',
        authorRole: 'inquilino',
      },
      {
        id: 'tl-28-2',
        status: 'orcamento_aprovado',
        title: 'Orçamento Aprovado',
        description: 'Orçamento de R$ 290,00 aprovado pela Imobiliária.',
        timestamp: '09/09/2026 às 10:00',
        authorName: 'Aliança Imobiliária',
        authorRole: 'imobiliaria',
      },
      {
        id: 'tl-28-3',
        status: 'em_execucao',
        title: 'Execução do Reparo',
        description:
          'Técnico Lucas Almeida realizou o alinhamento da chapa-testa e lubrificação técnica.',
        timestamp: '10/09/2026 às 14:00',
        authorName: 'Lucas Almeida',
        authorRole: 'prestador',
      },
      {
        id: 'tl-28-4',
        status: 'concluido',
        title: 'Serviço Concluído e Avaliado',
        description: 'Inquilino confirmou a resolução e avaliou com 5 estrelas.',
        timestamp: '10/09/2026 às 17:30',
        authorName: 'André Siqueira',
        authorRole: 'inquilino',
      },
    ],
    completion: {
      id: 'comp-1028',
      ticketId: 't-1028',
      completionDate: '10/09/2026 às 16:30',
      servicesPerformed:
        'Desmontagem da fechadura digital, realinhamento milimétrico do batente, troca das pilhas alcalinas industriais e lubrificação com spray de grafite seco.',
      materialsUsed: '4 pilhas alcalinas AA duracell, calço de ajuste em aço inox.',
      warrantyMonths: 6,
      observations: 'Testado 15 vezes com biometria e senha na presença do morador.',
      beforePhotos: [
        'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=600',
      ],
      afterPhotos: [
        'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=600',
      ],
      tenantConfirmed: true,
      tenantConfirmedAt: '10/09/2026 às 17:15',
    },
    evaluation: {
      id: 'eval-1028',
      ticketId: 't-1028',
      rating: 5,
      solved: true,
      satisfactory: true,
      punctual: true,
      comments:
        'Excelente atendimento! O técnico Lucas foi super pontual, educado e a fechadura ficou perfeita.',
      createdAt: '10/09/2026 17:30',
    },
    chatMessages: [
      {
        id: 'msg-28-1',
        ticketId: 't-1028',
        senderRole: 'inquilino',
        senderName: 'André Siqueira',
        message: 'Serviço finalizado com sucesso. Muito obrigado pela rapidez!',
        timestamp: '10/09/2026 17:20',
      },
    ],
  },
  {
    id: 't-1029',
    protocol: '#1029',
    createdAt: '2026-05-22 14:30',
    updatedAt: '2026-05-24 16:00',
    tenantName: 'Mariana Costa',
    tenantPhone: '(11) 98123-4567',
    tenantEmail: 'mariana.costa@email.com',
    address: 'Rua das Acácias, 450 - Apto 402',
    neighborhood: 'Pinheiros, São Paulo - SP',
    propertyType: 'apartamento',
    environment: 'Cozinha',
    category: 'eletrica',
    description: 'Tomada 20A da lava-louças com mal contato.',
    photos: [],
    urgency: 'normal',
    preferredPeriod: 'manha',
    status: 'concluido',
    assignedAgencyId: 'imob-alianca',
    assignedAgencyName: 'Aliança Gestão Imobiliária',
    assignedCompanyId: 'emp-casapronta',
    assignedCompanyName: 'Casa Pronta Manutenções',
    assignedTechnicianId: 'tech-jose',
    assignedTechnicianName: 'José Lima',
    lastActionAt: '2026-05-24 16:00',
    timeline: [
      {
        id: 'tl-29-1',
        status: 'chamado_aberto',
        title: 'Chamado Aberto',
        description: 'Troca de tomada.',
        timestamp: '22/05/2026 às 14:30',
        authorName: 'Mariana Costa',
        authorRole: 'inquilino',
      },
      {
        id: 'tl-29-2',
        status: 'concluido',
        title: 'Concluído',
        description: 'Módulo de tomada novo instalado e testado.',
        timestamp: '24/05/2026 às 16:00',
        authorName: 'José Lima',
        authorRole: 'prestador',
      },
    ],
    chatMessages: [],
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    ticketId: 't-1024',
    protocol: '#1024',
    clientName: 'Mariana Costa',
    clientPhone: '(11) 98123-4567',
    address: 'Rua das Acácias, 450 - Apto 402',
    neighborhood: 'Pinheiros, São Paulo - SP',
    agencyName: 'Aliança Imóveis',
    serviceType: 'Vistoria Hidráulica & Orçamento',
    description: 'Vistoria de vazamento no sifão e torneira de bancada.',
    technicianId: 'tech-carlos',
    technicianName: 'Carlos Santos',
    teamName: 'Equipe Hidráulica',
    date: '2026-09-13',
    startTime: '08:00',
    endTime: '09:30',
    priority: 'alta',
    status: 'concluido',
    tenantConfirmed: true,
  },
  {
    id: 'apt-2',
    ticketId: 't-1026',
    protocol: '#1026',
    clientName: 'Camila Toledo',
    clientPhone: '(11) 98999-1122',
    address: 'Rua Oscar Freire, 89 - Casa 3',
    neighborhood: 'Cerqueira César, São Paulo - SP',
    agencyName: 'Aliança Imóveis',
    serviceType: 'Emergência Elétrica',
    description: 'Disjuntor geral desarmando e cheiro de queimado.',
    technicianId: 'tech-jose',
    technicianName: 'José Lima',
    teamName: 'Equipe Elétrica',
    date: '2026-09-13',
    startTime: '09:30',
    endTime: '12:00',
    priority: 'emergencial',
    status: 'em_atendimento',
    tenantConfirmed: true,
  },
  {
    id: 'apt-3',
    clientName: 'Carlos Eduardo',
    clientPhone: '(11) 98455-1234',
    address: 'Rua Bela Cintra, 620 - Apto 51',
    neighborhood: 'Consolação, São Paulo - SP',
    agencyName: 'Aliança Imóveis',
    serviceType: 'Vistoria de Pintura de Desocupação',
    description: 'Conferência de pintura e massa corrida para entrega de chaves.',
    technicianId: 'tech-joao',
    technicianName: 'João Silva',
    teamName: 'Equipe Pintura',
    date: '2026-09-13',
    startTime: '11:00',
    endTime: '12:30',
    priority: 'normal',
    status: 'agendado',
    tenantConfirmed: true,
  },
  {
    id: 'apt-4',
    ticketId: 't-1025',
    protocol: '#1025',
    clientName: 'Roberto Nunes',
    clientPhone: '(11) 97234-8899',
    address: 'Av. Paulista, 1200 - Apto 84',
    neighborhood: 'Bela Vista, São Paulo - SP',
    agencyName: 'Aliança Imóveis',
    serviceType: 'Reparo de Infiltração',
    description: 'Abertura de forro e troca de tubulação de esgoto do banheiro.',
    technicianId: 'tech-carlos',
    technicianName: 'Carlos Santos',
    teamName: 'Equipe Hidráulica',
    date: '2026-09-13',
    startTime: '14:00',
    endTime: '16:00',
    priority: 'alta',
    status: 'confirmado',
    tenantConfirmed: true,
  },
  {
    id: 'apt-5',
    clientName: 'Dra. Beatriz',
    clientPhone: '(11) 99881-2233',
    address: 'Av. Brigadeiro Luís Antônio, 3400 - Conj 92',
    neighborhood: 'Jardim Paulista, São Paulo - SP',
    agencyName: 'Aliança Imóveis',
    serviceType: 'Instalação de Fechadura Digital',
    description: 'Instalação de fechadura eletrônica em porta de vidro.',
    technicianId: 'tech-lucas',
    technicianName: 'Lucas Almeida',
    teamName: 'Equipe Esquadrias & Fechaduras',
    date: '2026-09-13',
    startTime: '16:00',
    endTime: '17:30',
    priority: 'normal',
    status: 'agendado',
    tenantConfirmed: true,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    ticketId: 't-1024',
    protocol: '#1024',
    title: 'Orçamento Disponível para Aprovação',
    message:
      'O orçamento do chamado #1024 (R$ 380,00) foi enviado pela Casa Pronta e aguarda aprovação da Imobiliária.',
    timestamp: 'Hoje às 11:30',
    read: false,
    type: 'warning',
    targetRoles: ['imobiliaria', 'inquilino'],
  },
  {
    id: 'notif-2',
    ticketId: 't-1025',
    protocol: '#1025',
    title: 'Atendimento Agendado para Hoje',
    message:
      'Seu atendimento para o chamado #1025 está agendado para hoje às 14:00 com o técnico Carlos Santos.',
    timestamp: 'Hoje às 08:30',
    read: false,
    type: 'info',
    targetRoles: ['inquilino', 'prestador', 'empresa'],
  },
  {
    id: 'notif-3',
    ticketId: 't-1026',
    protocol: '#1026',
    title: 'Chamado Emergencial em Andamento',
    message: 'Técnico José Lima iniciou atendimento de emergência elétrica na Rua Oscar Freire.',
    timestamp: 'Hoje às 10:00',
    read: true,
    type: 'urgent',
    targetRoles: ['empresa', 'imobiliaria'],
  },
  {
    id: 'notif-4',
    ticketId: 't-1028',
    protocol: '#1028',
    title: 'Chamado Concluído e Avaliado',
    message:
      'O chamado #1028 foi finalizado com sucesso pelo técnico Lucas Almeida e recebeu avaliação 5 estrelas!',
    timestamp: '10/09/2026',
    read: true,
    type: 'success',
    targetRoles: ['inquilino', 'imobiliaria', 'empresa', 'prestador'],
  },
];
